name: Run tests
on:
  push:
    branches:
      - "*"

jobs:
  typecheck_and_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: biblioteksentralen/github-actions/node-setup@main
      - run: npm run test-ci
      